### ISSUE TITLE
Replace static create function pointer with a better solution

### ISSUE THREAD

**Issue by emilwestergren** [vidhance/android-camera-wrapper#31]

**Comment by sebastianbaginski** [comment]
@emilwestergren is someone working on this ? you mentioned some time ago that you'd like me to work on the C++ part more, so do you think I could start here ? or maybe I could do something else in the wrapper.
I think @davidpiuva is doing fine with the `draw` part on his own (I can always help with PR)

**Comment by emilwestergren** [comment]
Sure, please suggest your solution before implementing it though.

**Comment by sebastianbaginski** [comment]
I need to read through the code first, I'm not yet familiar with it. I will open a PR and we can discuss more.

**Comment by emilwestergren** [comment]
I can explain the problem to you if that is quicker.

**Comment by emilwestergren** [comment]
Do you consider this solved or do you have another improvement in mind?

**Comment by sebastianbaginski** [comment]
Currently I do not have much time to work on this. If you are happy with this one then close this issue.

Since the function is known at compile time it could be possible to give the correct VideoProcessor class as parameter to a generic CameraWrapper class, but I'm not sure if the code could get more clean than a simple static function in each compilation unit.
